title: Eduardo Lávaque

author:
    name: Eduardo Lávaque
    email: eduanlavaque@gmail.com

permalink: /:year/:month/:title.html

markdown: redcarpet
highlighter: pygments
gems:
    - jekyll-sitemap
